acromap = {
    'ACS': 'Acute coronary syndrome',
    'AD/HD': 'Attention deficit hyperactivity disorder',
    'ADHD': 'Attention deficit hyperactivity disorder',
    'aGVHD': 'Acute graft-versus-host disease',
    'AGVHD': 'Acute graft-versus-host disease',
    'ALL': 'Acute Lymphoblastic Leukemia',
    'ALS': 'Amyotrophic lateral sclerosis',
    'AMD': 'Age-related macular degeneration',
    'AMI': 'Acute myocardial infarction',
    'AML': 'Acute myeloid leukemia',
    'A.R.D.S.': 'Acute respiratory distress syndrome',
    'ARDS': 'Acute respiratory distress syndrome',
    'ASCVD': 'Atherosclerotic Cardiovascular Disease',
    'ATL': 'Adult T-Cell Leukemia',
    'ATTR-CM': 'Transthyretin Amyloid Cardiomyopathy',
    'B-ALL': 'B-Cell Acute Lymphoblastic Leukemia',
    'BPH': 'Benign Prostatic Hyperplasia',
    'C3G': 'Complement 3 Glomerulopathy',
    'CABG': 'Coronary artery bypass graft',
    'CAD': 'Coronary Artery Disease',
    'CAPD': 'Continuous Ambulatory Peritoneal Dialysis',
    'CHF': 'Chronic Heart Failure',
    'CIDP': 'Chronic inflammatory demyelinating polyradiculoneuropathy',
    'CLL': 'Chronic lymphocytic leukemia',
    'CML': 'Chronic Myeloid Leukemia',
    'CMV': 'Cytomegalovirus',
    'COPD': 'Chronic obstructive pulmonary disease',
    'EPOC': 'Chronic obstructive pulmonary disease',
    'CPAP': 'Continuous positive airway pressure units',
    'CTEPH': 'Chronic Thromboembolic Pulmonary Hypertension',
    'DDD': 'Degenerative Disc Disease',
    'DLBCL': 'Diffuse Large B-Cell Lymphoma',
    'EPP': ' Erythropoietic Protoporphyria',
    'FAP': 'Familial Amyloid Polyneuropathy',
    'FLU': 'Influenza',
    'FSAD': 'Female Sexual Arousal Disorder',
    'GAD': 'Generalised Anxiety Disorder',
    'GCT': 'Giant cell tumors',
    'GERD': 'Gastroesophageal Reflux Disease',
    'GIST': 'Gastrointestinal Stromal Tumors',
    'GVHD': 'Graft versus host disease',
    'HBV': 'Hepatitis B virus',
    'HCC': 'Hepatocellular carcinoma',
    'HCMV': 'Human cytomegalovirus',
    'HCV': 'Hepatitis C virus',
    'HES': 'Hypereosinophilic Syndrome',
    'HHT': 'Hereditary hemorrhagic telangiectasia',
    'HPV': 'Human Papillomavirus',
    'HRT': 'Hormone replacement therapy',
    'HSIL': 'High-grade squamous intraepithelial lesions',
    'IBD': 'Inflammatory bowel disease',
    'IBS': 'Irritable bowel syndrome',
    'ICD': 'Implantable Cardioverter Defibrillator',
    'ITP': 'Immune Thrombocytopenia',
    'IVF': 'In vitro fertilisation',
    'LVH': 'Left Ventricular Hypertrophy',
    'MDD': 'Major Depressive Disorder',
    'MDS': 'Myelodysplastic Syndrome',
    'MGUS': 'Monoclonal Gammopathy of Undetermined significance',
    'MS': 'Multiple sclerosis',
    'MSS': 'Microsatellite stable Metastatic Colorectal Cancer',
    'NAFLD': 'Nonalcoholic Fatty Liver Disease',
    'NASH': 'Non-Alcoholic Steatohepatitis',
    'NHL': 'Non-Hodgkin Lymphoma',
    'NOMID': 'Neonatal-Onset Multisystem Inflammatory Disease',
    'NSCLC': 'Non-Small-Cell Lung Cancer',
    'OCD': 'Obsessive compulsive disorder',
    'PAR': 'Persistent allergic rhinitis',
    'PBC': 'Primary biliary cholangitis',
    'PCOS': 'Polycystic ovary syndrome',
    'PHN': 'Postherpetic Neuralgia',
    'PPHN': 'Persistent Pulmonary Hypertension of the Newborn',
    'PTSD': 'Post Traumatic Stress Disorder',
    'RA': 'Rheumatoid Arthritis',
    'RSV': 'Respiratory Syncytial Virus',
    'RTI': 'Respiratory Tract Infection',
    'SCLC': 'Small Cell Lung Cancer',
    'SIADH': 'Syndrome of Inappropriate Antidiuretic Hormone Secretion',
    'SIRS': 'Systemic inflammatory response syndrome',
    'SLE': 'Systemic Lupus Erythematosus',
    'STEMI': 'ST Elevation Myocardial Infarction',
    'T1DM': 'Type 1 diabetes mellitus',
    'T2DM': 'Type 2 diabetes mellitus',
    'TAVI': 'Transcatheter Bioprosthetic Aortic Valve Implantation',
    'TB': 'Tubeculosis',
    'UC': 'Ulcerative Colitis',
    'VIH': 'HIV'
}