# Functions and tagging rules for countries


def fix_raw_countries(series):
    # Fix territory names containing commas
    # Fix "two territories in one name" bugs
    # Fix "words glued together" bugs
    part_keywords = 'republic|province|occupied|south|state of'
    return (
        series
        .str.replace(r'etc\.;?', '', case=False, regex=True)
        .str.replace(fr'([^,;]+),([^,;]*({part_keywords})[^,;]*)', r'\1\2',
                     case=False, regex=True)
        .str.replace('Virgin Islands, British', 'Virgin Islands (British)',
                     case=False, regex=False)
        .str.replace('Virgin Islands, U.S.', 'Virgin Islands (U.S.)',
                     case=False, regex=False)
        .str.replace('Korea, North', "Korea Democratic People's Republic of",
                     case=False, regex=False)
        .str.replace('Korea, South', "Korea Republic of", case=False,
                     regex=False)
        .str.replace('thailand', 'Thailand', case=False,
                     regex=True)  # Fix case bug
        .str.replace('china', 'China', case=False, regex=True)  # Fix case bug
        .str.replace(r'([a-z\)])(Czech)', r'\1;\2', regex=True)  # 2-in-one bug
        .str.replace(r'([a-z\)])(Dominican)', r'\1;\2',
                     regex=True)  # 2-in-one bug
        .str.replace(r'([a-z\)])(South)', r'\1;\2', regex=True)  # 2-in-one bug
        .str.replace(r'(Japan)\s+(South)', r'\1;\2', regex=True)  # 2-in-one bug
        .str.replace(r'(Japan)\s+(Republic)', r'\1;\2',
                     regex=True)  # 2-in-one bug
        .str.replace(r'(USA)\s+(Part B)', r'\1;\2', regex=True)  # 2-in-one bug
        .str.replace(r'(United States)\s+and\s+(Canada)', r'\1;\2',
                     regex=True)  # 2-in-one bug
        .str.replace(r'(North America)\s+(South America)', r'\1;\2',
                     regex=True)  # 2-in-one bug
        .str.replace(r'(Middle East)\s+(South-Eastern Asia)', r'\1;\2',
                     regex=True)  # 2-in-one bug
        .str.replace(r'([a-z\)])([A-Z])', r'\1 \2', regex=True)  # glued words
    )


territories_qtspec = {
    None: r'\d+ countr',  # e.g. "10 countries",
    'Afghanistan': 'afg',
    # African block
    'Central African Republic': 'central afr',
    'South Africa': [['south', 'afri']],
    'Africa': 'africa',
    #
    'Albania': 'albania',
    'Algeria': 'a[rl]gi?er',
    'American Samoa': r'americ.*samoa',
    'Samoa': 'samoa',
    'Andorra': 'andor',
    'Angola': 'angola',
    'Anguilla': 'anguilla',
    'Antarctica': 'antarctica',
    'Antigua and Barbuda': ['antigua', 'barbuda'],
    'Armenia': 'armenia',
    'Aruba': 'aruba',
    'Argentina': 'argent',
    'Australia': [r'^aus$', 'australia', 'austlaria', 'norfolk'],
    'Austria': [r'^aut$', 'austr'],
    'Azerbaijan': 'azerb',
    'Bahamas': 'bahamas',
    'Bahrain': 'bahrain',
    'Bangladesh': 'bangladesh',
    'Barbados': 'barbados',
    'Belgium': [r'^bel$', r'be[rl]g'],
    'Belarus': 'belarus',
    'Belize': 'beliz',
    'Benin': 'benin',
    'Bermuda': 'bermuda',
    'Bhutan': 'bhutan',
    'Venezuela': 'venezuela',
    'Bolivia': 'boliv',
    'Caribbean Netherlands': ['bonaire', 'eustatius', 'saba'],
    'Bosnia and Herzegovina': 'bosnia',
    'Botswana': 'botswana',
    'Brazil': r'bra[sz]il',
    'British Indian Ocean Territory': [['british', 'indian']],
    'Brunei': 'brunei',
    'Bulgaria': 'bulgar',
    'Burkina Faso': 'burkina',
    'Burundi': 'burundi',
    'Cambodia': r'cambod?ia',
    'Cameroon': 'cameroon',
    'Canada': r'cana?da',
    'Cape Verde': r'cape\sverde',
    'Cayman Islands': 'cayman',
    'Central America': r'central\s+america',
    'Chad': 'chad',
    'Chile': r'chili?e',
    'Cocos (Keeling) Islands': 'cocos',
    'Colombia': r'col[ou]mbia',
    'Christmas Island': 'christmas',
    'Comoros': 'comoros',
    'Congo': 'congo',
    'Cook Islands': 'cook',
    'Costa Rica': 'costa rica',
    "Côte d'Ivoire": 'ivoi?r',
    'Croatia': 'croatia',
    'Cuba': 'cuba',
    'Curaçao': 'cura[cç]ao',
    'Cyprus': 'cyprus',
    'Czechia': [r'c?[zh]ech', r'^cze$'],
    'Denmark': [r'^dnk$', r'd[ae]nmark', 'greenland'],
    'Djibouti': 'djibouti',
    'Dominican Republic': [['dominica', 'republic']],
    'Dominica': 'dominica',
    'Ecuador': 'ecuador',
    'Egypt': 'egypt',
    'El Salvador': 'salvador',
    'Eritrea': 'eritrea',
    'Estonia': 'estonia',
    'Eswatini': ['eswatini', 'swaziland'],
    'Ethiopia': r'ethi?opia',
    'European Union': [r'^eu$', 'europe'],
    'Falkland Islands': 'falkland',
    'Finland': ['fin', r'[aå]land\s+isla'],
    'Faroe Islands': 'faroe',
    'Fiji': 'fiji',
    'France': ['fra', ['fre', 'republi']],
    'French Guiana': 'guiana',
    'French Polynesia': 'polynesia',
    'French Southern and Antarctic Lands': [['fre', 'south']],    
    'Gabon': 'gabon',
    'Gambia': 'gambia',
    'South Georgia and the South Sandwich Islands': [['georgia', 'south']],
    'Georgia': 'georgia',
    'Germany': [r'^deu$', 'gery?ma'],
    'Ghana': 'ghana',
    'Gibraltar': 'gibraltar',
    'Greece': ['greece', 'hellenic'],
    'Grenada': 'grenada',
    'Guadeloupe': 'guadeloupe',
    'Guam': 'guam',
    'Guatemala': 'guatemala',
    'Guayana': 'gua?yana',
    'Guernsey': 'guernsey',
    # Guinea block
    'Equatorial Guinea': [['equator', 'guinea']],
    'Guinea-Bissau': [['biss[ae]u', 'guinea']],
    'Papua New Guinea': [['papua', 'guinea']],
    'Guinea': 'guinea',
    #
    'Haiti': 'haiti',
    'Heard Island and McDonald Islands': ['heard', 'mcdonald'],
    'Honduras': 'honduras',
    'Iceland': 'iceland',
    'India': ['india', r'\binida'],
    'Indonesia': 'indonesia',
    'Iran': 'iran',
    'Iraq': 'iraq',
    'Israel': 'isr[ae]{2}',
    'Italy': r'\bita',
    'Jamaica': 'jamaica',
    'Jordan': 'jordan',
    # Asia-Japan block
    'Asia except Japan': [['asia', 'except', 'japan']],
    'South-Eastern Asia': [['south', 'asia']],
    'Asia': 'asia',
    'Japan': 'japan',
    # Koreas
    'Korea (DPRK)': [['korea', 'democrat'], ['korea', 'north']],
    'Korea (ROK)': ['kor', 'krea'],
    # China-Thai block
    'Taiwan': [r'aiwi?an', 'tiwan', 'taipei', 'twn'],
    'Hong Kong': [r'hong\s?[ck]ong', 'hkg'],
    'China': ['anhui', 'beijing', 'chongqing', 'guangd[ou]ng', 'hebei',
              'henan', 'hina', 'jiangsu', r'maca[ou]', 'shaanxi', 'shandong',
              'shanghai', 'tianjin', 'tibet', r'zhong\s?guo', 'zhejiang',
              r'\bchi', 'chii?na', 'chain', '^cn?ini?a', "people's republic",
              'chna', 'chnia'],
    'Thailand': [r'ah?iland', r'\btha', r'bang?kok', 'banlat',
                 r'ha[dt]\s?yai', 'pathum', r'mae\s?tha', 'yasothon'],
    'Hungary': r'hu[nm]',
    #
    'Kazakhstan': 'kaza',
    'Kenya': 'kenya',
    'Kiribati': 'kiribati',
    'Kosovo': 'kosovo',
    'Kuwait': 'kuwait',
    'Kyrgyzstan': 'kyrg',
    'Laos': r'la[ou]',
    'Latvia': r'lato?via',
    'Lebanon': 'leban',
    'Lesotho': 'lesotho',
    'Liberia': 'liberia',
    'Libya': 'libya',
    'Liechtenstein': 'liechtenstein',
    'Lithuania': r'lith?ua',
    'Luxembourg': 'luxembourg',
    'Madagascar': 'madagascar',
    'Marshall Islands': 'marshall',
    'Macedonia': 'macedonia',
    'Malaysia': r'malay?s',
    'Malawi': 'malawi',
    'Maldives': 'maldives',
    'Mali': r'\bmali',
    'Malta': 'malta',
    'Martinique': 'martinique',
    'Mauritania': 'mauritania',
    'Mauritius': 'mauritius',
    'Mayotte': 'mayotte',
    'Mexico': 'm[eé]x',
    'Micronesia': ['micronesia', ['federated', 'states']],
    'Middle East': 'middle east',
    'Moldova': ['mold', 'modalvia'],
    'Monaco': 'monaco',
    'Mongolia': r'mo?ng',
    'Montenegro': 'montenegro',
    'Montserrat': 'montserrat',
    'Morocco': 'morocco',
    'Mozambique': 'mozambique',
    'Myanmar': 'myanmar',
    'Namibia': 'namibia',
    'Nauru': 'nauru',
    'Netherlands': [r'ner?ther?land', 'neder', 'holland', 'nld'],
    'Nepal': 'nepal',
    'New Caledonia': 'caledonia',
    'New Zealand': r'new zea?land',
    'Nicaragua': 'nicaragua',
    'Nigeria': 'nigeria',
    'Niger': 'niger',
    'Niue': 'niue',
    'Northern Mariana Islands': 'mariana',
    'Norway': ['bouvet', 'norw'],
    'Oceania': 'oceania',
    'Oman': r'\boman',
    'Pakistan': 'pakistan',
    'Palau': 'palau',
    'Palestine': 'palestin',
    'Panama': 'panama',
    'Paraguay': 'paragua',
    'Peru': 'peru',
    'Philippines': r'phill?i?p?pines',
    'Pitcairn Islands': 'pitcairn',
    'Poland': ['pland', r'\bpol'],
    'Portugal': 'portug',
    'Puerto Rico': 'puerto',
    'Qatar': 'qatar',
    'Réunion': r'r[ée]union',
    'Romania': r'r[ou]man',
    'Russia': r'russ?i',
    'Rwanda': 'rwanda',
    'Saint Barthélemy': r'barth[eé]lemy',
    'Saint Helena': 'helena',
    'Saint Kitts and Nevis': 'kitts',
    'Saint Lucia': 'lucia',
    'Saint Martin': r'maa?rt[ie]n',
    'Saint Pierre and Miquelon': 'pierre',
    'Saint Vincent and the Grenadines': 'vincent',
    'San Marino': 'marino',
    'São Tomé and Príncipe': r'pr[íi]ncipe',
    'Saudi Arabia': [['saud', 'arab'], 'ksa'],
    'Senegal': 'senegal',
    'Serbia': 'serbia',
    'Seychelles': 'seychelles',
    'Singapore': ['singapore?', 'sgp'],
    'Sierra Leone': 'sierra leone',
    'Slovakia': ['slovak', r'^sk$'],
    'Slovenia': 'slovenia',
    'Solomon Islands': 'solomon',
    'Somalia': 'somalia',
    'South Sudan': [['south', 'sudan']],
    'Svalbard and Jan Mayen': 'svalbard',
    'Sudan': 'sudan',
    'Spain': [r'^esp$', r'sp[ae]in'],
    'Sri Lanka': 'sri lanka',
    'Suriname': 'surinam',
    'Switzerland': [r'^che$', 'switzer', 'swiss'],
    'Sweden': r'swee?d',
    'Syria': 'syria',
    'Tajikistan': r'ta[jy]ikistan',
    'Tanzania': 'tanzania',
    'East Timor': 'timor',
    'Togo': 'togo',
    'Tonga': 'tonga',
    'Trinidad and Tobago': 'trinidad',
    'Tunisia': 'tunis',
    'Turks and Caicos Islands': 'caicos',
    'Turkey': [r't[ur]{2}ke', 'rkiye'],
    'Turkmenistan': 'turkmen',
    'Tuvalu': 'tuvalu',
    # UK, US and America block
    'British Virgin Islands': [['virgin', 'british']],
    'U.S. Virgin Islands': [['virgin', r'u\.s\.']],
    'United Kingdom': [r'ed king?', 'england', 'scotland', 'gbr',
                       r'\buk\b', r'u\.k\.', 'britain', 'jersey',
                       ['northern', 'ireland'], ['isle', 'man'],
                       'unidet kingdum', 'wales'],
    'Ireland': r'\bire?l',
    'North America': [['north', 'america']],
    'South America': [['south', 'america']],
    'United States': [r'^american?$', r'nite?d sta', 'usa',
                      r'\bus\b', r'u\.s\.'],
    #
    'Uganda': 'uganda',
    'Ukraine': r'ukra?in',
    'United Arab Emirates': ['uae', 'arab emirates'],
    'Uruguay': 'uruguay',
    'Uzbekistan': 'uzbek',
    'Vanuatu': 'vanuatu',
    'Vatican': 'vatican',
    'Vietnam': ['viet', 'vnm'],
    'Wallis and Futuna': ['wallis', 'futuna'],
    'Western Sahara': 'sahara',
    'Worldwide': ['global', 'world'],
    'Yemen': 'yemen',
    'Zaire': 'zair',
    'Zambia': 'zamb',
    'Zimbabwe': 'zimb',
    'Former Yugoslavia': 'yugo'
}
